### ISSUE TITLE
can't verify plex server after plex update

### ISSUE THREAD

**Issue by sequence83** [Tautulli/Tautulli-Issues#229]
Hi there,
i've noticed after updated plex server version to 1.18.9.2578 tautulli can't connect to plex server. In logs there is 

"Tautulli Pmsconnect :: Unable to parse XML for get_current_activity: 'NoneType' object has no attribute 'getElementsByTagName'. Failed to access uri endpoint /status/sessions. Is your server maybe accepting SSL connections only? HTTPSConnectionPool"

before that update tautulli works perfectly fine. 
It's tautulli bug? or new version will appear?
Thanks for any advice.

**Comment by samwiseg0** [comment]
Issues is not the place for support. Please continue to use discord. Also, please be patient as we will respond when we can.
